# Site settings
title: sensorika documentation site
motto: Sensorika. Documentation
email: stub@stub.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sensorika.info" # the base hostname & protocol for your site
twitter_username: 404
github_username:  sensorika

# Build settings
# markdown: kramdown
# markdown: maruku
markdown: redcarpet
#redcarpet:
#  extensions: [tables]
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
